### ISSUE TITLE
Usage with axum >= 0.7.0

### ISSUE THREAD

**Issue by noctux** [vi/tokio-listener#3]
Hi,

thank you for this convenient library which promises to very conveniently solve one of my problems :P
While looking through this library, I stumbled accross `examples/clap_axum.rs`, which seems to be incompatible with axum >= 0.7 and/or hyper >= 1.0 to me:

Hyper 1.0  apparently dropped the `hyper::Server` interface, and [axum followed suit as it just reexported `hyper::Server` as `axum::Server`](https://tokio.rs/blog/2023-11-27-announcing-axum-0-7-0) but instead provides an [`axum::serve` interface itself](https://docs.rs/axum/latest/axum/fn.serve.html), which, however, is spcifically tied to `TcpListener`s.

Axum has since also updated their examples (including the [unix domain socket example](https://github.com/tokio-rs/axum/blob/e63cc49f5545f0323122898c12981a7815da995b/examples/unix-domain-socket/src/main.rs#L62) which is probably most relevant to tokio-listeners usage), effectively replicating hyper's previous `Server` functionality by a custom accept loop.
I believe (without too much certainty, I'm quite new to using axum) that this is now also required for tokio-listener, as it does not offer the `TcpListener` interface. Furthermore, probably a mechanism akin to what is already implemented for the `tonic010` feature might be required to correctly attribute the correct `ConnectionInfo` type/have a custom `ListenerConnectInfo `compatible with [`Router::into_make_service_with_connect_info`](https://docs.rs/axum/latest/axum/struct.Router.html#method.into_make_service_with_connect_info) for situations where connection info is of interest.

Is my assessment correct? Is there any clever way of using tokio-listener together with axum >= 0.7 without too much hassle? What is the recommended way as of now? What would `examples/clap_axum.rs` look like nowadays?

Thank you for providing this library in the first place, and also thank you for taking the time to read this bug report :) (Furthermore: I'm sorry if I've missed something obvious and thus wasted some of your time).
  ~ Simon

**Comment by vi** [comment]
Axum/hyper support code in `tokio-listener` needs a complete rewrite to support up to date versions.

> ... Is my assessment correct? ...

I haven't yet read the comment in detail.

I'm trying to import a copy of [`axum::serve`](https://docs.rs/axum/latest/axum/serve/index.html) as a module of `tokio-listener` (and adapt it to `tokio-listener`'s types).

Maybe that would be enough.

**Comment by noctux** [comment]
> I'm trying to import a copy of [`axum::serve`](https://docs.rs/axum/latest/axum/serve/index.html) as a module of `tokio-listener` (and adapt it to `tokio-listener`'s types).
> 
> Maybe that would be enough.

Sure, this should work fine as well and be nearly as convenient as using the upstream variation. Downside is probably that this incurs some recurring costs (changes to `axum::server` might occasionally require backports), but I guess this is a manageable amount of code and probably stable enough.

**Comment by vi** [comment]
Implemented `tokio_listener::axum07` (in git, not yet on crates.io).

Please check if everything's OK with it.

Avoiding significant amount of duplicated code with the actual `axum::serve` is an open question.

**Comment by vi** [comment]
Asked at Axum's discussions: https://github.com/tokio-rs/axum/discussions/2472

**Comment by noctux** [comment]
Hey, thank you for the really fast response!

Just tested it with `tokio-listener = { git = "https://github.com/vi/tokio-listener.git", features = ["serde", "axum07"] }` at `git+https://github.com/vi/tokio-listener.git#57c81e7389541d2898f5546652f66a8a5569d9ef` which works like a breeze (tested http and unix listen modes so far, but I see no reasons why it should not work for socket activation as well.
(N.B.: I've only tested without ConnectionInfo as my example is agnostic to client-identities).

So this issue can probably be considered resolved from my side :)
Also a good idea to raise this as an axum discussion (even though the responses read a bit disappointing), so I guess your current solution seems to be the way to go.

Thank you for your efforts!

**Comment by vi** [comment]
Published `v0.3.0` with the changes.

**Comment by noctux** [comment]
Tested my project against the released `v0.3.0` as well, all seems to work. Thanks once more for your efforts!
